# This workflow will build and package the nodejs service and deploy to AWS via Beanstalk

name: PittsCurb-Service-CI/CD

on:
  push:
    branches: [ master ]
  # Turning this off so it only builds and deploys after a merge is completed which results in a push
  #  pull_request:
  #  branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
          
    - name: Yarn Install
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: install # will run `yarn install` command
    - name: Yarn Build
      uses: borales/actions-yarn@v2.0.0
      with:
        cmd: build # will run `yarn build` command
    - name: Zip build
      run: zip buildartifact.zip build/* package.json
    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'  
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v10
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: PittsCurb-Service
        environment_name: PittscurbService-Prod
        version_label: "PittsCurb-Service-${{ steps.format-time.outputs.replaced }}"
        region: us-east-1  
        deployment_package: buildartifact.zip
